<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function shila_quiz_preprocess_layout(&$variables) {
  switch ($variables['content']['#entity_type']) {
    case 'node':
      switch ($variables['content']['#bundle']) {
        case 'quiz':
          if (!isset($variables['button_text']) || empty($variables['button_text'])) {
            $variables['button_text'] = t('Show result');
          }
          $variables['result_heading'] = t('Result');
          $variables['result_heading'] .= ':';
          _shila_quiz_copy_content_variables($variables);
          if (!isset($variables['results']['field_quiz_results']['#items'])) {
            unset($variables['results']);
          }
          break;
      }
      break;

    case 'paragraph':
      switch ($variables['content']['#bundle']) {
        case 'quiz_answer_option':
          $entity = $variables['content']['#entity'];
          $parentEntity = $entity->getParentEntity();
          $delta = NULL;
          $refEntities = $parentEntity->get('field_quiz_answer_options')->referencedEntities();
          foreach ($refEntities as $i => $refEntity) {
            if ($entity->id() == $refEntity->id()) {
              $delta = $i;
              break;
            }
          }
          $variables['option_group_name'] = 'question_' . $parentEntity->id();
          $variables['option_value'] = 'option_' . $delta;
        case 'quiz_question':
        case 'quiz_result':
          _shila_quiz_copy_content_variables($variables);
          break;
      }
      break;
  }
}

function _shila_quiz_copy_content_variables(&$variables) {
  // Copy each region variable to root, but only if a root variable with that
  // name does not already exist.
  /** @var \Drupal\Core\Layout\LayoutDefinition $layout */
  $layout = $variables['layout'];
  foreach ($layout->getRegionNames() as $name) {
    if (!isset($variables[$name]) && isset($variables['content'][$name])) {
      $variables[$name] = $variables['content'][$name];
    }
  }
}
