<?php

/**
 * Add information about the entity and its parent to the pattern context of
 * quiz_answer_option paragraphs.
 *
 * Implements template_preprocess_ds_entity_view().
 */
function shila_quiz_preprocess_ds_entity_view(&$variables) {
  if ($variables['content']['#entity_type'] == 'paragraph'
    && $variables['content']['#bundle'] == 'quiz_answer_option'
    && isset($variables['content']['#type'])
    && $variables['content']['#type'] == 'pattern')
  {
    $entity = $variables['content']['#entity'];
    $parentEntity = $entity->getParentEntity();
    $delta = NULL;
    $refEntities = $parentEntity->get('field_quiz_answer_options')->referencedEntities();
    foreach ($refEntities as $i => $refEntity)  {
      if ($entity->id() == $refEntity->id()) {
        $delta = $i;
        break;
      }
    }
    $variables['content']['#context']['parent_id'] = $parentEntity->id();
    $variables['content']['#context']['delta'] = $delta;
  }
}

/**
 * Set pattern variables based on data in the pattern context.
 *
 * Implements hook_preprocess_HOOK().
 */
function shila_quiz_preprocess_pattern_shila_quiz_answer_option(&$variables) {
  $variables['option_group_name'] = 'question_' . $variables['context']->getProperty('parent_id');
  $variables['option_value'] = 'option_' . $variables['context']->getProperty('delta');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function shila_quiz_preprocess_pattern_shila_quiz(&$variables) {
  // Unset results variable if empty.
  if (!isset($variables['results']['field_quiz_results']['#items'])) {
    unset($variables['results']);
  }

  // Set default translated button text variable if required. The translation is
  // done here so that the Twig component template does not have to use the
  // Drupal specific translation filter.
  if (!isset($variables['button_text']) || empty($variables['button_text'])) {
    $variables['button_text'] = t('Show result');
  }

  $variables['result_heading'] = t('Result') . ':';
}
